-- Clear existing data to prevent duplicates if run multiple times
DELETE FROM "public"."fun_facts";

-- Insert new, longer fun facts
INSERT INTO "public"."fun_facts" (english_text) VALUES
('A group of flamingos is not just a flock; it is called a "flamboyance." This vibrant term perfectly captures the essence of these social birds, known for their bright pink feathers. They get this distinct color from pigments in the algae and crustaceans they eat.'),
('While many countries choose powerful animals like lions or eagles, Scotland''s national animal is the unicorn. This mythical creature was adopted in the 15th century as a symbol of purity, innocence, and power, representing the nation''s pride and its historical conflicts with England, whose symbol was the lion.'),
('Honey is one of the few foods that never spoils. Its remarkable longevity is due to its low moisture content and high acidity, creating an inhospitable environment for bacteria. Archaeologists have discovered pots of honey in ancient Egyptian tombs over 3,000 years old that are still perfectly preserved.'),
('An octopus has a surprisingly complex circulatory system featuring three hearts. Two of the hearts work exclusively to pump blood through the gills, while the third, larger heart circulates blood to the rest of the body. Interestingly, this systemic heart stops beating when the octopus swims, which is why they prefer crawling.'),
('Wombats are the only known animals in the world that produce cube-shaped feces. Scientists believe the unique shape is formed by the varying elasticity of their intestinal walls. This geometric poop helps them mark their territory, as the flat-sided cubes do not roll away easily on rocks and logs.'),
('The Eiffel Tower''s height is not constant throughout the year. Being made of iron, it experiences thermal expansion, causing it to grow taller in the summer heat and shrink in the winter cold. The difference can be up to 15 centimeters as the metal structure expands when heated.'),
('Botanically speaking, bananas are classified as berries because they grow from a flower with a single ovary and contain multiple seeds. Conversely, strawberries, despite their name, are not true berries. They are technically "aggregate fruits," as they develop from a flower that has more than one ovary.'),
('The shortest war in recorded history was the Anglo-Zanzibar War on August 27, 1896. The conflict began after the Sultan of Zanzibar died and a successor took power without British approval. The war lasted a mere 38 minutes before the Zanzibari forces surrendered following a decisive naval bombardment.'),
('The axolotl, a species of salamander native to Mexico, possesses extraordinary regenerative abilities. It can regrow entire lost limbs, parts of its brain, and even its spinal cord without any scarring. This remarkable healing power has made it a key subject of scientific research into cellular regeneration.'),
('The Turritopsis dohrnii is often called the "immortal jellyfish." When faced with physical damage or starvation, it can revert completely to its earliest stage of life, a polyp, and begin its life cycle anew. This unique ability to cycle between mature and juvenile stages potentially allows it to live forever.');