DO $$
DECLARE
    fact_uuid UUID;
BEGIN
    -- Fact 21
    INSERT INTO public.og_facts (fact_text, category, subcategory) VALUES ('There is a "sponge" in space; Saturn''s moon Hyperion is a bizarre, porous body with a chaotic, tumbling rotation. Its low density and irregular, sponge-like appearance suggest it''s mostly water ice with very little rock.', 'Science', 'Space') RETURNING id INTO fact_uuid;
    INSERT INTO public.fact_translations (fact_id, language, beginner_text, intermediate_text, advanced_text) VALUES (fact_uuid, 'Spanish', 'Hay una "esponja" en el espacio. Es Hiperión, una luna de Saturno. Es porosa, irregular y gira de forma caótica.', 'La luna de Saturno, Hiperión, es como una esponja espacial. Es un cuerpo poroso con una rotación caótica. Su baja densidad y apariencia irregular sugieren que es principalmente hielo de agua.', 'Hiperión, una de las lunas de Saturno, es un cuerpo celeste poroso y extraño, a menudo descrito como una "esponja espacial". Posee una rotación caótica e irregular, y su baja densidad sugiere que está compuesto mayormente por hielo de agua con muy poca roca.');

    -- Fact 22
    INSERT INTO public.og_facts (fact_text, category, subcategory) VALUES ('In ancient Athens, citizens could vote to exile a politician for ten years without specific charges. This process, called ostracism, was done by writing the person''s name on a pottery shard (ostrakon) to preemptively remove someone thought to be a threat to democracy.', 'History', 'Political History') RETURNING id INTO fact_uuid;
    INSERT INTO public.fact_translations (fact_id, language, beginner_text, intermediate_text, advanced_text) VALUES (fact_uuid, 'Spanish', 'En la antigua Atenas, los ciudadanos exiliaban a políticos por diez años. Escribían el nombre en un trozo de cerámica.', 'En la antigua Atenas, los ciudadanos podían votar para exiliar a un político por diez años sin cargos específicos. Este proceso, llamado ostracismo, se usaba para eliminar amenazas a la democracia.', 'En la antigua Atenas, mediante un proceso conocido como ostracismo, los ciudadanos podían votar para exiliar a un político durante diez años sin necesidad de cargos formais. El nombre se escribía en un fragmento de cerámica (ostrakon) para eliminar preventivamente a quien se considerara una amenaza para la democracia.');

    -- Fact 23
    INSERT INTO public.og_facts (fact_text, category, subcategory) VALUES ('The world''s oldest surviving parliament is the Icelandic Althing, founded in 930 AD. Originally an open-air assembly at Þingvellir, chieftains met annually to establish laws and settle disputes for the Icelandic Commonwealth.', 'History', 'Political History') RETURNING id INTO fact_uuid;
    INSERT INTO public.fact_translations (fact_id, language, beginner_text, intermediate_text, advanced_text) VALUES (fact_uuid, 'Spanish', 'El parlamento más antiguo del mundo es el Althing de Islandia. Fue fundado en el año 930. Los jefes se reunían para crear leyes.', 'El parlamento más antiguo que aún existe es el Althing de Islandia, fundado en el 930 d.C. Originalmente, era una asamblea al aire libre donde los jefes se reunían para hacer leyes.', 'El parlamento en funcionamiento más antiguo del mundo es el Althing islandés, fundado en el año 930 d.C. Originalmente una asamblea al aire libre en Þingvellir, los jefes tribales se reunían anualmente para establecer leyes y resolver disputas.');

    -- Fact 24
    INSERT INTO public.og_facts (fact_text, category, subcategory) VALUES ('The Anglo-Zanzibar War of 1896 is the shortest recorded war in history, lasting between 38 and 45 minutes. The conflict began after the Sultan of Zanzibar refused to step down, leading to a decisive British naval bombardment of his palace.', 'History', 'Political History') RETURNING id INTO fact_uuid;
    INSERT INTO public.fact_translations (fact_id, language, beginner_text, intermediate_text, advanced_text) VALUES (fact_uuid, 'Spanish', 'La guerra más corta de la historia duró unos 40 minutos. Fue la Guerra Anglo-Zanzibariana en 1896. Los británicos bombardearon un palacio.', 'La Guerra Anglo-Zanzibariana de 1896 es la más corta registrada, durando entre 38 y 45 minutos. El conflicto empezó cuando el sultán se negó a renunciar, lo que provocó un bombardeo británico.', 'La Guerra Anglo-Zanzibariana de 1896 ostenta el récord de ser la guerra más corta de la historia, con una duración de entre 38 y 45 minutos. El conflicto se desencadenó después de que el sultán de Zanzíbar se negara a abdicar, lo que resultó en un decisivo bombardeo naval británico a su palacio.');

    -- Fact 25
    INSERT INTO public.og_facts (fact_text, category, subcategory) VALUES ('In 1859, the United States and Great Britain nearly went to war over a pig. The "Pig War" was a border dispute over the San Juan Islands that escalated when an American farmer shot a British-owned pig, leading to a military standoff that was ultimately resolved peacefully.', 'History', 'Political History') RETURNING id INTO fact_uuid;
    INSERT INTO public.fact_translations (fact_id, language, beginner_text, intermediate_text, advanced_text) VALUES (fact_uuid, 'Spanish', 'En 1859, Estados Unidos y Gran Bretaña casi van a la guerra por un cerdo. Un granjero estadounidense mató a un cerdo británico.', 'En 1859, Estados Unidos y Gran Bretaña casi entran en guerra por un cerdo. La "Guerra del Cerdo" fue una disputa fronteriza que escaló cuando un granjero estadounidense le disparó a un cerdo británico.', 'En 1859, Estados Unidos y Gran Bretaña estuvieron al borde de la guerra por un cerdo. La "Guerra del Cerdo" fue una disputa fronteriza que se intensificó cuando un granjero estadounidense mató a un cerdo de propiedad británica, lo que condujo a una tensión militar que finalmente se resolvió pacíficamente.');

    -- Fact 26
    INSERT INTO public.og_facts (fact_text, category, subcategory) VALUES ('The Holy Roman Empire''s constitution was partially codified by the Golden Bull of 1356. This decree, issued by Emperor Charles IV, established the method of electing an emperor by seven prince-electors, a system that lasted for over 400 years.', 'History', 'Political History') RETURNING id INTO fact_uuid;
    INSERT INTO public.fact_translations (fact_id, language, beginner_text, intermediate_text, advanced_text) VALUES (fact_uuid, 'Spanish', 'La Bula de Oro de 1356 fue una ley importante. Estableció cómo elegir al emperador. Siete príncipes votaban por él.', 'La Bula de Oro de 1356 codificó parte de la constitución del Sacro Imperio Romano. Este decreto estableció el método para elegir al emperador, que era votado por siete príncipes electores.', 'La constitución del Sacro Imperio Romano Germánico fue parcialmente codificada por la Bula de Oro de 1356. Este decreto, emitido por el emperador Carlos IV, estableció el método de elección del emperador por un colegio de siete príncipes electores, un sistema que perduró más de 400 años.');

    -- Fact 27
    INSERT INTO public.og_facts (fact_text, category, subcategory) VALUES ('England''s first detailed written constitution was the "Instrument of Government" of 1653. Drafted during the rule of Oliver Cromwell, it created the position of Lord Protector and was one of the first such documents in the modern world.', 'History', 'Political History') RETURNING id INTO fact_uuid;
    INSERT INTO public.fact_translations (fact_id, language, beginner_text, intermediate_text, advanced_text) VALUES (fact_uuid, 'Spanish', 'La primera constitución escrita de Inglaterra fue el "Instrumento de Gobierno". Se creó en 1653 durante el gobierno de Oliver Cromwell.', 'La primera constitución escrita de Inglaterra fue el "Instrumento de Gobierno" de 1653. Creada bajo el gobierno de Oliver Cromwell, estableció el cargo de Lord Protector y fue un documento pionero.', 'La primera constitución escrita y detallada de Inglaterra fue el "Instrumento de Gobierno" de 1653. Redactado durante el mandato de Oliver Cromwell, creó el cargo de Lord Protector y fue uno de los primeros documentos de este tipo en el mundo moderno.');

    -- Fact 28
    INSERT INTO public.og_facts (fact_text, category, subcategory) VALUES ('New Zealand became the first self-governing country to grant all women the right to vote in national elections in 1893. This landmark legislation was the result of years of campaigning by suffragists led by Kate Sheppard.', 'History', 'Political History') RETURNING id INTO fact_uuid;
    INSERT INTO public.fact_translations (fact_id, language, beginner_text, intermediate_text, advanced_text) VALUES (fact_uuid, 'Spanish', 'Nueva Zelanda fue el primer país autónomo en dar el voto a las mujeres. Esto ocurrió en 1893 gracias a muchas activistas.', 'En 1893, Nueva Zelanda se convirtió en el primer país autónomo en otorgar a todas las mujeres el derecho al voto en elecciones nacionales. Fue el resultado de años de campaña de sufragistas.', 'Nueva Zelanda se convirtió en 1893 en el primer país autónomo del mundo en conceder a todas las mujeres el derecho al voto en las elecciones nacionales. Esta legislación histórica fue el resultado de años de campaña por parte de las sufragistas, lideradas por Kate Sheppard.');

    -- Fact 29
    INSERT INTO public.og_facts (fact_text, category, subcategory) VALUES ('Switzerland was one of the last Western countries to grant women the right to vote. Women only gained suffrage in federal elections in 1971, and the last canton, Appenzell Innerrhoden, was forced to allow women to vote in local elections by a federal court decision in 1990.', 'History', 'Political History') RETURNING id INTO fact_uuid;
    INSERT INTO public.fact_translations (fact_id, language, beginner_text, intermediate_text, advanced_text) VALUES (fact_uuid, 'Spanish', 'En Suiza, las mujeres votaron tarde. Pudieron votar en elecciones federales en 1971. En un cantón, votaron recién en 1990.', 'Suiza fue uno de los últimos países occidentales en conceder el voto a las mujeres. Lo obtuvieron en elecciones federales en 1971, y el último cantón las dejó votar en 1990 por orden judicial.', 'Suiza fue uno de los últimos países occidentales en conceder el sufragio femenino. Las mujeres obtuvieron el derecho al voto en las elecciones federales recién en 1971, y el último cantón, Appenzell Rodas Interiores, fue obligado a permitirlo en elecciones locales por un tribunal federal en 1990.');

    -- Fact 30
    INSERT INTO public.og_facts (fact_text, category, subcategory) VALUES ('In the early Soviet Union, there was a widespread campaign called "Latinization" to replace the Cyrillic and Arabic scripts of over 50 minority languages with the Latin alphabet. The policy was abruptly reversed in the late 1930s in favor of Cyrillization.', 'History', 'Political History') RETURNING id INTO fact_uuid;
    INSERT INTO public.fact_translations (fact_id, language, beginner_text, intermediate_text, advanced_text) VALUES (fact_uuid, 'Spanish', 'En la Unión Soviética, se intentó usar el alfabeto latino. Querían cambiar las escrituras de más de 50 idiomas. Luego, la política cambió.', 'En la Unión Soviética hubo una campaña de "latinización" para reemplazar las escrituras cirílica y árabe de más de 50 idiomas. Sin embargo, la política se revirtió en los años 30.', 'En la temprana Unión Soviética, hubo una campaña de "latinización" para reemplazar los alfabetos cirílico y árabe de más de 50 lenguas minoritarias por el latino. La política fue revertida abruptamente a finales de la década de 1930 en favor de la cirilización.');

    -- Fact 31
    INSERT INTO public.og_facts (fact_text, category, subcategory) VALUES ('The Republic of Venice elected its leader, the Doge, through an incredibly complex system of lotteries and voting. This multi-stage process was designed to minimize corruption, factionalism, and the influence of powerful families.', 'History', 'Political History') RETURNING id INTO fact_uuid;
    INSERT INTO public.fact_translations (fact_id, language, beginner_text, intermediate_text, advanced_text) VALUES (fact_uuid, 'Spanish', 'La República de Venecia elegía a su líder, el Dogo. Usaban un sistema muy complejo de loterías y votos para evitar la corrupción.', 'La República de Venecia elegía a su líder, el Dogo, con un sistema muy complejo de sorteos y votaciones. El objetivo era reducir la corrupción y la influencia de las familias poderosas.', 'La República de Venecia elegía a su líder, el Dogo, a través de un sistema increíblemente complejo que combinaba loterías y votaciones. Este proceso de múltiples etapas fue diseñado para minimizar la corrupción, el faccionalismo y la influencia de las familias poderosas.');

    -- Fact 32
    INSERT INTO public.og_facts (fact_text, category, subcategory) VALUES ('The United States nearly ratified a "Titles of Nobility Amendment" in the early 19th century. If passed, it would have stripped citizenship from any American who accepted a title of nobility from a foreign power without the consent of Congress.', 'History', 'Political History') RETURNING id INTO fact_uuid;
    INSERT INTO public.fact_translations (fact_id, language, beginner_text, intermediate_text, advanced_text) VALUES (fact_uuid, 'Spanish', 'Estados Unidos casi aprueba una enmienda sobre la nobleza. Quitaría la ciudadanía a quien aceptara un título de nobleza extranjero.', 'A principios del siglo XIX, Estados Unidos casi ratifica una enmienda sobre títulos de nobleza. De haber sido aprobada, le habría quitado la ciudadanía a cualquier estadounidense que aceptara un título nobiliario extranjero.', 'A principios del siglo XIX, Estados Unidos estuvo a punto de ratificar la "Enmienda sobre Títulos de Nobleza". De haber sido aprobada, habría despojado de su ciudadanía a cualquier estadounidense que aceptara un título de nobleza de una potencia extranjera sin el consentimiento del Congreso.');

    -- Fact 33
    INSERT INTO public.og_facts (fact_text, category, subcategory) VALUES ('In 1932, Australia''s military waged a "Great Emu War." The army was deployed to combat a massive emu population damaging crops in Western Australia. The emus proved surprisingly difficult to hunt, and the military operation was widely seen as a failure.', 'History', 'Political History') RETURNING id INTO fact_uuid;
    INSERT INTO public.fact_translations (fact_id, language, beginner_text, intermediate_text, advanced_text) VALUES (fact_uuid, 'Spanish', 'En 1932, el ejército de Australia luchó contra emúes. Los emúes dañaban los cultivos. Los soldados no pudieron vencerlos y la operación fracasó.', 'En 1932, el ejército australiano libró la "Gran Guerra del Emú" para controlar una plaga de emúes que dañaban cultivos. Sorprendentemente, los emúes fueron difíciles de cazar y la operación fue un fracaso.', 'En 1932, el ejército de Australia emprendió la "Gran Guerra del Emú". Se desplegaron militares para combatir una enorme población de emúes que dañaba los cultivos en Australia Occidental. Los emúes resultaron ser un objetivo esquivo y la operación fue considerada un fracaso.');

    -- Fact 34
    INSERT INTO public.og_facts (fact_text, category, subcategory) VALUES ('The shortest-serving British Prime Minister was George Canning, who died in office in 1827 after only 119 days. His brief tenure was marked by his efforts to manage complex foreign policy issues, including the Greek War of Independence.', 'History', 'Political History') RETURNING id INTO fact_uuid;
    INSERT INTO public.fact_translations (fact_id, language, beginner_text, intermediate_text, advanced_text) VALUES (fact_uuid, 'Spanish', 'George Canning fue el primer ministro británico con el mandato más corto. Estuvo en el cargo solo 119 días en 1827.', 'El primer ministro británico que menos tiempo ha estado en el cargo fue George Canning. Murió en 1827 después de solo 119 días, durante los cuales manejó asuntos de política exterior.', 'El primer ministro británico con el mandato más breve fue George Canning, quien falleció en el cargo en 1827 tras solo 119 días. Su corto periodo se caracterizó por sus esfuerzos en la gestión de complejos asuntos de política exterior, como la Guerra de Independencia de Grecia.');

    -- Fact 35
    INSERT INTO public.og_facts (fact_text, category, subcategory) VALUES ('In 1925, a border incident where a Greek soldier was shot after allegedly chasing his runaway dog across the Bulgarian border escalated into a brief conflict known as the "War of the Stray Dog." The League of Nations intervened to prevent a full-scale war.', 'History', 'Political History') RETURNING id INTO fact_uuid;
    INSERT INTO public.fact_translations (fact_id, language, beginner_text, intermediate_text, advanced_text) VALUES (fact_uuid, 'Spanish', 'En 1925, hubo una guerra por un perro. Un soldado griego cruzó la frontera persiguiendo a su perro y le dispararon.', 'En 1925, un incidente fronterizo conocido como la "Guerra del Perro Callejero" casi causa una guerra total. Un soldado griego fue abatido tras cruzar la frontera búlgara persiguiendo a su perro.', 'En 1925, un incidente fronterizo en el que un soldado griego fue abatido tras supuestamente perseguir a su perro a través de la frontera búlgara, escaló a un breve conflicto conocido como la "Guerra del Perro Callejero". La Sociedad de Naciones intervino para evitar una guerra a gran escala.');

    -- Fact 36
    INSERT INTO public.og_facts (fact_text, category, subcategory) VALUES ('One of the world''s first female diplomats was Diana Abgar, who was appointed honorary consul for the First Republic of Armenia to Japan in 1920. She used her position to aid Armenian Genocide refugees and advocate for her fledgling nation.', 'History', 'Political History') RETURNING id INTO fact_uuid;
    INSERT INTO public.fact_translations (fact_id, language, beginner_text, intermediate_text, advanced_text) VALUES (fact_uuid, 'Spanish', 'Diana Abgar fue una de las primeras diplomáticas del mundo. En 1920, fue cónsul de Armenia en Japón. Ayudó a muchos refugiados.', 'Una de las primeras diplomáticas del mundo fue Diana Abgar, nombrada cónsul honoraria de Armenia en Japón en 1920. Usó su cargo para ayudar a los refugiados del Genocidio Armenio.', 'Diana Abgar fue una de las primeras diplomáticas del mundo, nombrada cónsul honoraria de la Primera República de Armenia en Japón en 1920. Utilizó su cargo para ayudar a los refugiados del Genocidio Armenio y abogar por su incipiente nación.');

    -- Fact 37
    INSERT INTO public.og_facts (fact_text, category, subcategory) VALUES ('The last time the army of Liechtenstein was deployed for a military engagement was in 1866. An army of 80 men was sent to guard an Italian mountain pass; they saw no combat and returned home with 81 men, having made a new friend.', 'History', 'Political History') RETURNING id INTO fact_uuid;
    INSERT INTO public.fact_translations (fact_id, language, beginner_text, intermediate_text, advanced_text) VALUES (fact_uuid, 'Spanish', 'La última vez que el ejército de Liechtenstein fue a la guerra fue en 1866. Se fueron 80 soldados. Regresaron 81 porque hicieron un amigo.', 'La última vez que el ejército de Liechtenstein participó en una acción militar fue en 1866. Un grupo de 80 hombres fue enviado, no combatió y regresó a casa con 81 hombres, tras hacer un amigo.', 'La última vez que el ejército de Liechtenstein fue desplegado para una misión militar fue en 1866. Un contingente de 80 hombres fue enviado a vigilar un paso montañoso italiano; no entraram em combate e regressaram a casa sendo 81, pois tinham feito um novo amigo.');

    -- Fact 38
    INSERT INTO public.og_facts (fact_text, category, subcategory) VALUES ('The ancient Roman historian Suetonius claimed that Emperor Caligula planned to make his favorite horse, Incitatus, a consul. While likely an exaggeration to portray Caligula as insane, it highlighted his contempt for the Roman Senate.', 'History', 'Political History') RETURNING id INTO fact_uuid;
    INSERT INTO public.fact_translations (fact_id, language, beginner_text, intermediate_text, advanced_text) VALUES (fact_uuid, 'Spanish', 'El emperador Calígula quería que su caballo fuera cónsul. El caballo se llamaba Incitatus. Esto mostraba su desprecio por el Senado.', 'El historiador Suetonio afirmó que el emperador Calígula planeaba nombrar cónsul a su caballo favorito, Incitatus. Probablemente era una exageración para mostrar el desprecio de Calígula por el Senado romano.', 'El historiador romano Suetonio afirmó que el emperador Calígula planeaba nombrar cónsul a su caballo favorito, Incitatus. Aunque probablemente fue una exageración para retratar a Calígula como un demente, el relato subraya su desprecio por el Senado romano.');

    -- Fact 39
    INSERT INTO public.og_facts (fact_text, category, subcategory) VALUES ('The "Ministry of All the Talents" was a British national unity government formed in 1806. It brought together various political factions during the Napoleonic Wars and notably abolished the slave trade in the British Empire in 1807.', 'History', 'Political History') RETURNING id INTO fact_uuid;
    INSERT INTO public.fact_translations (fact_id, language, beginner_text, intermediate_text, advanced_text) VALUES (fact_uuid, 'Spanish', 'En 1806, se formó en Gran Bretaña el "Ministerio de Todos los Talentos". Este gobierno abolió el comercio de esclavos en 1807.', 'El "Ministerio de Todos los Talentos" fue un gobierno de unidad nacional británico formado en 1806. Unió a varias facciones políticas y abolió el comercio de esclavos en el Imperio Británico en 1807.', 'El "Ministerio de Todos los Talentos" fue un gobierno de unidad nacional británico formado en 1806 durante las Guerras Napoleónicas. Reunió a diversas facciones políticas y es notable por haber abolido el comercio de esclavos en el Imperio Británico en 1807.');

    -- Fact 40
    INSERT INTO public.og_facts (fact_text, category, subcategory) VALUES ('In 1923, Adolf Hitler attempted a failed coup in Munich known as the "Beer Hall Putsch." His subsequent arrest and trial gave him a national platform, and he used his time in prison to write his political manifesto, Mein Kampf.', 'History', 'Political History') RETURNING id INTO fact_uuid;
    INSERT INTO public.fact_translations (fact_id, language, beginner_text, intermediate_text, advanced_text) VALUES (fact_uuid, 'Spanish', 'En 1923, Adolf Hitler intentó un golpe de estado en Múnich. El golpe fracasó y fue a la cárcel. Allí escribió su libro "Mi Lucha".', 'En 1923, Adolf Hitler intentó un fallido golpe de estado en Múnich, conocido como el "Putsch de la Cervecería". Su arresto y juicio le dieron fama y en prisión escribió su manifiesto "Mi Lucha".', 'En 1923, Adolf Hitler lideró un intento fallido de golpe de estado en Múnich, conocido como el "Putsch de la Cervecería". Su posterior arresto y juicio le proporcionaron una plataforma nacional, y aprovechó su tiempo en prisión para escribir su manifiesto político, "Mein Kampf".');

    -- Fact 41
    INSERT INTO public.og_facts (fact_text, category, subcategory) VALUES ('The micronation of Sealand is located on a former World War II sea fort in the North Sea. Occupied by the family of Paddy Roy Bates since 1967, it has its own flag, currency, and constitution, though it is not recognized by any sovereign state.', 'History', 'Political History') RETURNING id INTO fact_uuid;
    INSERT INTO public.fact_translations (fact_id, language, beginner_text, intermediate_text, advanced_text) VALUES (fact_uuid, 'Spanish', 'Sealand es una micronación en un fuerte marino. Está en el Mar del Norte. Tiene su propia bandera y moneda, pero no es un país oficial.', 'La micronación de Sealand se encuentra en un antiguo fuerte marino de la Segunda Guerra Mundial. Ocupada por una familia desde 1967, tiene su propia bandera y moneda, pero ningún país la reconoce.', 'La micronación de Sealand está ubicada en un antiguo fuerte marítimo de la Segunda Guerra Mundial en el Mar del Norte. Ocupada por la familia de Paddy Roy Bates desde 1967, posee su propia bandera, moneda y constitución, aunque no es reconocida por ningún estado soberano.');

    -- Fact 42
    INSERT INTO public.og_facts (fact_text, category, subcategory) VALUES ('The world''s northernmost capital city is Reykjavik, Iceland. Located at a latitude of 64°08 N, it sits just south of the Arctic Circle, making it the top-most capital of any sovereign state on the planet.', 'Geography', 'World Records') RETURNING id INTO fact_uuid;
    INSERT INTO public.fact_translations (fact_id, language, beginner_text, intermediate_text, advanced_text) VALUES (fact_uuid, 'Spanish', 'La capital más al norte del mundo es Reikiavik, en Islandia. Está muy cerca del Círculo Polar Ártico.', 'Reikiavik, la capital de Islandia, es la capital más septentrional del mundo. Se encuentra justo al sur del Círculo Polar Ártico, lo que la convierte en la capital de un estado soberano más al norte.', 'La capital más septentrional del mundo es Reikiavik, Islandia. Situada en la latitud 64°08'' N, se encuentra justo al sur del Círculo Polar Ártico, lo que la posiciona como la capital de un estado soberano ubicada más al norte del planeta.');

    -- Fact 43
    INSERT INTO public.og_facts (fact_text, category, subcategory) VALUES ('The point on Earth''s surface farthest from its center is the summit of Mount Chimborazo in Ecuador. Due to the planet''s equatorial bulge, its peak is over 2,072 meters (6,800 feet) farther from the Earth''s core than Mount Everest''s summit.', 'Geography', 'World Records') RETURNING id INTO fact_uuid;
    INSERT INTO public.fact_translations (fact_id, language, beginner_text, intermediate_text, advanced_text) VALUES (fact_uuid, 'Spanish', 'El punto más lejano del centro de la Tierra es el Monte Chimborazo en Ecuador. Es por la forma de la Tierra.', 'La cima del Monte Chimborazo en Ecuador es el punto más alejado del centro de la Tierra. Debido al abultamiento ecuatorial del planeta, su cumbre está más lejos del núcleo que la del Monte Everest.', 'El punto de la superficie terrestre más alejado de su centro es la cumbre del volcán Chimborazo en Ecuador. Debido al abultamiento ecuatorial del planeta, su cima está más de 2,072 metros más lejos del núcleo terrestre que la cumbre del Monte Everest.');

    -- Fact 44
    INSERT INTO public.og_facts (fact_text, category, subcategory) VALUES ('The world''s largest salt flat is Salar de Uyuni in Bolivia, covering over 10,000 square kilometers (4,086 sq mi). This prehistoric lakebed is so vast and perfectly flat that NASA uses its surface to calibrate satellite sensors.', 'Geography', 'World Records') RETURNING id INTO fact_uuid;
    INSERT INTO public.fact_translations (fact_id, language, beginner_text, intermediate_text, advanced_text) VALUES (fact_uuid, 'Spanish', 'El salar más grande del mundo es el Salar de Uyuni en Bolivia. Es muy grande y plano. La NASA lo usa para calibrar satélites.', 'El desierto de sal más grande del mundo es el Salar de Uyuni en Bolivia, con más de 10,000 kilómetros cuadrados. Es tan plano que la NASA lo utiliza para calibrar los sensores de sus satélites.', 'El salar más grande del mundo es el Salar de Uyuni en Bolivia, que abarca más de 10,000 kilómetros cuadrados. Este lecho de un lago prehistórico es tan vasto y perfectamente plano que la NASA utiliza su superficie para calibrar los sensores de los satélites.');

    -- Fact 45
    INSERT INTO public.og_facts (fact_text, category, subcategory) VALUES ('The country with the longest total coastline is Canada, with an astonishing 202,080 kilometers (125,567 miles). Its shores meet three different oceans: the Atlantic, Pacific, and Arctic, encompassing thousands of islands.', 'Geography', 'World Records') RETURNING id INTO fact_uuid;
    INSERT INTO public.fact_translations (fact_id, language, beginner_text, intermediate_text, advanced_text) VALUES (fact_uuid, 'Spanish', 'Canadá es el país con la costa más larga del mundo. Mide 202,080 kilómetros. Sus costas tocan tres océanos diferentes.', 'Canadá tiene la costa más larga del mundo, con 202,080 kilómetros. Sus costas limitan con los océanos Atlántico, Pacífico y Ártico, e incluyen miles de islas.', 'El país con la línea costera más larga es Canadá, con una asombrosa extensión de 202,080 kilómetros. Sus costas se encuentran con tres océanos diferentes: el Atlántico, el Pacífico y el Ártico, abarcando miles de islas.');

    -- Fact 46
    INSERT INTO public.og_facts (fact_text, category, subcategory) VALUES ('The world''s tallest uninterrupted waterfall is Angel Falls in Venezuela. It cascades from the top of Auyán-tepui, with a total height of 979 meters (3,212 feet) and a single continuous plunge of 807 meters (2,648 feet).', 'Geography', 'World Records') RETURNING id INTO fact_uuid;
    INSERT INTO public.fact_translations (fact_id, language, beginner_text, intermediate_text, advanced_text) VALUES (fact_uuid, 'Spanish', 'La cascada más alta del mundo es el Salto Ángel en Venezuela. Mide 979 metros de altura. Su caída de agua no tiene interrupciones.', 'La cascada ininterrumpida más alta del mundo es el Salto Ángel en Venezuela. Cae desde la cima del Auyán-tepui y tiene una altura total de 979 metros.', 'La cascada ininterrumpida más alta del mundo es el Salto Ángel en Venezuela. Cae desde la cima del Auyán-tepui, con una altura total de 979 metros y una caída continua de 807 metros.');

    -- Fact 47
    INSERT INTO public.og_facts (fact_text, category, subcategory) VALUES ('The oldest desert in the world is the Namib Desert in southwestern Africa. It has endured arid or semi-arid conditions for at least 55 million years, creating a unique ecosystem with many endemic species adapted to the extreme dryness.', 'Geography', 'World Records') RETURNING id INTO fact_uuid;
    INSERT INTO public.fact_translations (fact_id, language, beginner_text, intermediate_text, advanced_text) VALUES (fact_uuid, 'Spanish', 'El desierto más antiguo del mundo es el de Namib en África. Tiene al menos 55 millones de años. Viven allí especies únicas.', 'El desierto de Namib, en el suroeste de África, es el más antiguo del mundo. Ha tenido condiciones áridas por al menos 55 millones de años, creando un ecosistema único con especies endémicas.', 'El desierto más antiguo del mundo es el de Namib, en el suroeste de África. Ha soportado condiciones áridas o semiáridas durante al menos 55 millones de años, lo que ha dado lugar a un ecosistema único con muchas especies endémicas adaptadas a la sequedad extrema.');

    -- Fact 48
    INSERT INTO public.og_facts (fact_text, category, subcategory) VALUES ('The largest single cave chamber by surface area is the Sarawak Chamber in Gunung Mulu National Park, Malaysia. At 1.66 million square feet, this enormous underground space is large enough to hold about 40 Boeing 747 airplanes.', 'Geography', 'World Records') RETURNING id INTO fact_uuid;
    INSERT INTO public.fact_translations (fact_id, language, beginner_text, intermediate_text, advanced_text) VALUES (fact_uuid, 'Spanish', 'La cámara de cueva más grande del mundo está en Malasia. Se llama la Cámara de Sarawak. Es tan grande que caben 40 aviones Boeing 747.', 'La cámara de cueva más grande por superficie es la Cámara de Sarawak en Malasia. Este enorme espacio subterráneo es lo suficientemente grande como para albergar unos 40 aviones Boeing 747.', 'La cámara de cueva individual más grande por superficie es la Cámara de Sarawak en el Parque Nacional Gunung Mulu, Malasia. Con 154,500 metros cuadrados, este enorme espacio subterráneo podría albergar unos 40 aviones Boeing 747.');

    -- Fact 49
    INSERT INTO public.og_facts (fact_text, category, subcategory) VALUES ('The world''s least populated capital city is Ngerulmud, Palau. Established in 2006, this purpose-built capital has a population of only a few hundred people, making it a quiet and remote seat of government.', 'Geography', 'World Records') RETURNING id INTO fact_uuid;
    INSERT INTO public.fact_translations (fact_id, language, beginner_text, intermediate_text, advanced_text) VALUES (fact_uuid, 'Spanish', 'La capital con menos gente es Ngerulmud, en Palaos. Fue fundada en 2006. Solo viven allí unos pocos cientos de personas.', 'Ngerulmud, la capital de Palaos, es la capital menos poblada del mundo. Fundada en 2006, tiene solo unos cientos de habitantes, lo que la convierte en una sede de gobierno muy tranquila.', 'La capital menos poblada del mundo es Ngerulmud, en Palaos. Establecida en 2006, esta capital planificada tiene una población de solo unos cientos de personas, lo que la convierte en una sede de gobierno remota y tranquila.');

    -- Fact 50
    INSERT INTO public.og_facts (fact_text, category, subcategory) VALUES ('The official highest temperature ever recorded on Earth was 56.7°C (134°F) in Death Valley, California, on July 10, 1913. This record was confirmed after a previous, higher reading in Libya was decertified by the World Meteorological Organization.', 'Geography', 'World Records') RETURNING id INTO fact_uuid;
    INSERT INTO public.fact_translations (fact_id, language, beginner_text, intermediate_text, advanced_text) VALUES (fact_uuid, 'Spanish', 'La temperatura más alta registrada en la Tierra fue de 56.7°C. Ocurrió en el Valle de la Muerte, California, en 1913.', 'La temperatura más alta registrada oficialmente en la Tierra fue de 56.7°C en el Valle de la Muerte, California, en 1913. Este récord se confirmó después de que se anulara uno anterior en Libia.', 'La temperatura más alta registrada oficialmente en la Tierra fue de 56.7°C en el Valle de la Muerte, California, el 10 de julio de 1913. Este récord fue validado después de que la Organización Meteorológica Mundial anulara un registro anterior más alto en Libia.');

    -- Fact 51
    INSERT INTO public.og_facts (fact_text, category, subcategory) VALUES ('The flattest country on Earth is the Maldives. This island nation, composed of coral atolls, has an average elevation of just 1.5 meters and its highest natural point is only about 5 meters above sea level, making it extremely vulnerable to rising seas.', 'Geography', 'World Records') RETURNING id INTO fact_uuid;
    INSERT INTO public.fact_translations (fact_id, language, beginner_text, intermediate_text, advanced_text) VALUES (fact_uuid, 'Spanish', 'Maldivas es el país más plano del mundo. Su altura promedio es de 1.5 metros. El punto más alto tiene solo 5 metros.', 'El país más plano de la Tierra es Maldivas. Esta nación de islas tiene una elevación promedio de solo 1.5 metros, lo que la hace muy vulnerable a la subida del nivel del mar.', 'Maldivas es el país más plano de la Tierra. Esta nación insular, compuesta por atolones de coral, tiene una elevación media de solo 1.5 metros y su punto natural más alto apenas alcanza los 5 metros sobre el nivel del mar, lo que la hace extremadamente vulnerable al aumento del nivel del mar.');

    -- Fact 52
    INSERT INTO public.og_facts (fact_text, category, subcategory) VALUES ('The world''s shortest international bridge is the 9.75-meter (32-foot) span connecting a small Canadian island to a larger U.S. island in the Thousand Islands archipelago. It crosses the border between Canada and the United States.', 'Geography', 'World Records') RETURNING id INTO fact_uuid;
    INSERT INTO public.fact_translations (fact_id, language, beginner_text, intermediate_text, advanced_text) VALUES (fact_uuid, 'Spanish', 'El puente internacional más corto del mundo mide 9.75 metros. Conecta una isla de Canadá con una de Estados Unidos.', 'El puente internacional más corto del mundo mide 9.75 metros y conecta una isla canadiense con una estadounidense en el archipiélago de las Mil Islas. Cruza la frontera entre ambos países.', 'El puente internacional más corto del mundo, con una longitud de 9.75 metros, conecta una pequeña isla canadiense con una isla estadounidense más grande en el archipiélago de las Mil Islas, cruzando la frontera entre Canadá y Estados Unidos.');

    -- Fact 53
    INSERT INTO public.og_facts (fact_text, category, subcategory) VALUES ('The highest commercially navigable lake in the world is Lake Titicaca, straddling the border of Peru and Bolivia in the Andes Mountains. It sits at an elevation of 3,812 meters (12,507 feet) above sea level.', 'Geography', 'World Records') RETURNING id INTO fact_uuid;
    INSERT INTO public.fact_translations (fact_id, language, beginner_text, intermediate_text, advanced_text) VALUES (fact_uuid, 'Spanish', 'El lago Titicaca es el lago navegable más alto del mundo. Está en Perú y Bolivia. Se encuentra a 3,812 metros de altura.', 'El lago Titicaca, ubicado en la frontera de Perú y Bolivia, es el lago comercialmente navegable más alto del mundo. Se encuentra a una altitud de 3,812 metros sobre el nivel del mar.', 'El lago navegable a mayor altitud del mundo es el Titicaca, situado en la cordillera de los Andes, en la frontera entre Perú y Bolivia. Se encuentra a una elevación de 3,812 metros sobre el nivel del mar.');

    -- Fact 54
    INSERT INTO public.og_facts (fact_text, category, subcategory) VALUES ('The most remote inhabited archipelago on Earth is Tristan da Cunha in the South Atlantic Ocean. This British Overseas Territory is over 2,400 kilometers (1,500 miles) from the nearest continental land, Saint Helena.', 'Geography', 'World Records') RETURNING id INTO fact_uuid;
    INSERT INTO public.fact_translations (fact_id, language, beginner_text, intermediate_text, advanced_text) VALUES (fact_uuid, 'Spanish', 'El archipiélago habitado más remoto es Tristán de Acuña. Está en el Océano Atlántico. La tierra más cercana está a 2,400 kilómetros.', 'Tristán de Acuña, en el Atlántico Sur, es el archipiélago habitado más remoto del mundo. Este territorio británico está a más de 2,400 kilómetros de la tierra continental más cercana.', 'El archipiélago habitado más remoto de la Tierra es Tristán de Acuña, en el Atlántico Sur. Este Territorio Británico de Ultramar se encuentra a más de 2,400 kilómetros de la masa continental más cercana, que es África.');

    -- Fact 55
    INSERT INTO public.og_facts (fact_text, category, subcategory) VALUES ('The world''s largest river island is Majuli, located in the Brahmaputra River in Assam, India. This island is a cultural hub for Neo-Vaishnavite culture but is progressively shrinking due to significant riverbank erosion.', 'Geography', 'World Records') RETURNING id INTO fact_uuid;
    INSERT INTO public.fact_translations (fact_id, language, beginner_text, intermediate_text, advanced_text) VALUES (fact_uuid, 'Spanish', 'La isla de río más grande del mundo es Majuli, en la India. Es un centro cultural importante. La isla se está haciendo más pequeña.', 'Majuli, en el río Brahmaputra en la India, es la isla fluvial más grande del mundo. Es un importante centro cultural, pero se está reduciendo progresivamente debido a la erosión del río.', 'La isla fluvial más grande del mundo es Majuli, situada en el río Brahmaputra, en Assam, India. Esta isla es un centro neurálgico de la cultura neovaishnavista, pero está disminuyendo de tamaño progresivamente debido a una importante erosión de sus riberas.');

    -- Fact 56
    INSERT INTO public.og_facts (fact_text, category, subcategory) VALUES ('The deepest ice on Earth is found at the Bentley Subglacial Trench in Antarctica. The ice sheet here reaches a depth of 4,776 meters (15,670 feet), with the base of the ice lying 2,555 meters (8,383 feet) below sea level.', 'Geography', 'World Records') RETURNING id INTO fact_uuid;
    INSERT INTO public.fact_translations (fact_id, language, beginner_text, intermediate_text, advanced_text) VALUES (fact_uuid, 'Spanish', 'El hielo más profundo de la Tierra está en la Antártida. Se encuentra en la Fosa Subglacial Bentley. El hielo allí tiene 4,776 metros de profundidad.', 'El hielo más profundo de la Tierra se encuentra en la Fosa Subglacial Bentley en la Antártida. La capa de hielo alcanza una profundidad de 4,776 metros, con su base a 2,555 metros bajo el nivel del mar.', 'El hielo más profundo de la Tierra se localiza en la Fosa Subglacial Bentley, en la Antártida. La capa de hielo alcanza aquí una profundidad de 4,776 metros, y la base del hielo se encuentra a 2,555 metros por debajo del nivel del mar.');

    -- Fact 57
    INSERT INTO public.og_facts (fact_text, category, subcategory) VALUES ('The place with the highest concentration of thunderstorms is near Lake Maracaibo in Venezuela. The "Catatumbo lightning" phenomenon occurs on average 297 days a year, with intense lightning storms lasting for hours.', 'Geography', 'World Records') RETURNING id INTO fact_uuid;
    INSERT INTO public.fact_translations (fact_id, language, beginner_text, intermediate_text, advanced_text) VALUES (fact_uuid, 'Spanish', 'Cerca del lago de Maracaibo en Venezuela hay muchas tormentas eléctricas. Este fenómeno se llama "Relámpago del Catatumbo". Ocurre casi todos los días.', 'El lugar con la mayor concentración de tormentas eléctricas está cerca del lago de Maracaibo en Venezuela. El fenómeno del "Relámpago del Catatumbo" ocurre un promedio de 297 días al año.', 'El lugar con la mayor concentración de tormentas eléctricas del mundo se encuentra cerca del lago de Maracaibo en Venezuela. Allí ocurre el fenómeno del "Relámpago del Catatumbo", con tormentas intensas que se producen un promedio de 297 días al año.');

    -- Fact 58
    INSERT INTO public.og_facts (fact_text, category, subcategory) VALUES ('The world''s largest monolith is Mount Augustus (Burringurrah) in Western Australia. Often mistaken for Uluru, it is more than twice its size, covering an area of about 4,795 hectares (11,850 acres).', 'Geography', 'World Records') RETURNING id INTO fact_uuid;
    INSERT INTO public.fact_translations (fact_id, language, beginner_text, intermediate_text, advanced_text) VALUES (fact_uuid, 'Spanish', 'El monolito más grande del mundo es el Monte Augusto en Australia. Es más del doble de grande que Uluru.', 'El monolito más grande del mundo es el Monte Augusto en Australia Occidental. A menudo se confunde con Uluru, pero es más del doble de su tamaño, cubriendo un área de 4,795 hectáreas.', 'El monolito más grande del mundo es el Monte Augusto (Burringurrah) en Australia Occidental. Frecuentemente confundido con Uluru, es en realidad más del doble de su tamaño, abarcando un área de aproximadamente 4,795 hectáreas.');

    -- Fact 59
    INSERT INTO public.og_facts (fact_text, category, subcategory) VALUES ('The longest place name in the world belongs to a hill in New Zealand: Taumatawhakatangihangakoauauotamateaturipukakapikimaungahoronukupokaiwhenuakitanatahu. The 85-letter name is of Māori origin.', 'Geography', 'World Records') RETURNING id INTO fact_uuid;
    INSERT INTO public.fact_translations (fact_id, language, beginner_text, intermediate_text, advanced_text) VALUES (fact_uuid, 'Spanish', 'El nombre de lugar más largo del mundo es de una colina en Nueva Zelanda. Tiene 85 letras y es de origen maorí.', 'El nombre de lugar más largo del mundo pertenece a una colina en Nueva Zelanda y tiene 85 letras. El nombre, de origen maorí, es Taumatawhakatangihangakoauauotamateaturipukakapikimaungahoronukupokaiwhenuakitanatahu.', 'El topónimo más largo del mundo pertenece a una colina en Nueva Zelanda: Taumatawhakatangihangakoauauotamateaturipukakapikimaungahoronukupokaiwhenuakitanatahu. Este nombre de 85 letras es de origen maorí.');

    -- Fact 60
    INSERT INTO public.og_facts (fact_text, category, subcategory) VALUES ('The country that spans the most time zones is France. When including its overseas territories, from French Polynesia to Réunion, France covers 12 different time zones, more than any other country.', 'Geography', 'World Records') RETURNING id INTO fact_uuid;
    INSERT INTO public.fact_translations (fact_id, language, beginner_text, intermediate_text, advanced_text) VALUES (fact_uuid, 'Spanish', 'Francia es el país con más zonas horarias. Si se cuentan sus territorios de ultramar, cubre 12 zonas horarias en total.', 'Francia es el país que abarca más zonas horarias. Incluyendo sus territorios de ultramar, como la Polinesia Francesa, el país cubre un total de 12 zonas horarias diferentes.', 'El país que abarca el mayor número de husos horarios es Francia. Al incluir sus territorios de ultramar, desde la Polinesia Francesa hasta la isla de la Reunión, Francia cubre 12 zonas horarias distintas, más que cualquier otra nación.');

    -- Fact 61
    INSERT INTO public.og_facts (fact_text, category, subcategory) VALUES ('The oceanic pole of inaccessibility, known as Point Nemo, is the place in the ocean that is farthest from land. Located in the South Pacific, the nearest landmass is over 2,688 kilometers (1,670 miles) away in any direction.', 'Geography', 'World Records') RETURNING id INTO fact_uuid;
    INSERT INTO public.fact_translations (fact_id, language, beginner_text, intermediate_text, advanced_text) VALUES (fact_uuid, 'Spanish', 'El Punto Nemo es el lugar del océano más alejado de la tierra. La tierra más cercana está a más de 2,688 kilómetros.', 'El Punto Nemo, también conocido como el polo oceánico de inaccesibilidad, es el lugar del océano más lejano de cualquier tierra. La masa de tierra más cercana está a más de 2,688 kilómetros.', 'El polo oceánico de inaccesibilidad, conocido como Punto Nemo, es el lugar del océano más alejado de cualquier masa terrestre. Ubicado en el Pacífico Sur, la tierra más cercana se encuentra a más de 2,688 kilómetros de distancia en cualquier dirección.');
END $$;